"""empty message

Revision ID: 0651b554ccad
Revises: 94a332431907
Create Date: 2020-09-19 15:02:48.437580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0651b554ccad'
down_revision = '94a332431907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lactose_intolerant', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('low_carb', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('vegan', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('vegetarian', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vegetarian')
    op.drop_column('user', 'vegan')
    op.drop_column('user', 'low_carb')
    op.drop_column('user', 'lactose_intolerant')
    # ### end Alembic commands ###
