"""empty message

Revision ID: 8a86ed0be5fb
Revises: 0651b554ccad
Create Date: 2020-09-19 17:00:58.236523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a86ed0be5fb'
down_revision = '0651b554ccad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('achievements', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'achievements')
    # ### end Alembic commands ###
