"""empty message

Revision ID: 94a332431907
Revises: 7dcca5db7463
Create Date: 2020-09-19 10:04:01.658491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a332431907'
down_revision = '7dcca5db7463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('date_consumed', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'date_consumed')
    # ### end Alembic commands ###
